parameters:
#    vivait_queue.example.class: Vivait\WorkerCommandBundle\Example

services:
#    vivait_queue.example:
#        class: %vivait_queue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
